#ifndef ADJUSTABLEPHYSICS2D_SHAPETYPE_H
#define ADJUSTABLEPHYSICS2D_SHAPETYPE_H

enum class ShapeType {
    Circle,
    AABB,
#ifndef USE_PRIMITIVES_ONLY
    Complex
#endif
};

#endif //ADJUSTABLEPHYSICS2D_SHAPETYPE_H
